version: '3.8'
services:
  test:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - '80:80'
      - '3000:3000'
    volumes:
      - '../:/opt/app/'
      - '../build:/var/www/html/'
